# Generated by Django 4.2 on 2023-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_review', models.TextField(verbose_name='Отзыв')),
                ('admin_answer', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=0)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
